art_echo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from artecho import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.index, name='index'),
    # added for html test viewing:
    path('card/', views.card, name='card'),
    path('add_root', views.add_root, name='add_root'),
    path('tree', views.tree_view, name='tree'),
    path('profileedit/<slug:slug>/', views.profile_edit, name='profile_edit'),
    path('profile/<slug:slug>/', views.profile, name='profile'),
    # html test urlpatters end here---
    path('artecho/', include('artecho.urls')),
    path('admin/', admin.site.urls),
    path('profile', views.profile, name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('delete_image/<int:image_id>/', views.delete_image, name='delete_image'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artecho/urls.py
from django.urls import path
from artecho import views

app_name = 'artecho'

urlpatterns = [
    path('', views.index, name='index'),
    path('addroot', views.add_root, name='add_root'),
    path('download/<slug:slug>/', views.download_image, name='download_image'),
    path('like_image/<int:image_id>/', views.like_image, name='like_image'),
    path('profile/<slug:slug>/', views.profile, name='profile'),
    path('addchild/<str:user_name>/<str:image_title>/', views.add_child, name='add_child'),
    path('card', views.card, name='card'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'), 
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('<str:user_name>/<str:image_title>/', views.tree_view, name='tree'),
    path('profileedit/<slug:slug>/', views.profile_edit, name='profile_edit'),
    path('search/', views.search_results, name="search"),
    path('delete_image/<int:image_id>/', views.delete_image, name='delete_image'),
]

artecho/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
 
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True, null = False)
    totalPosts = models.IntegerField(default = 0)
    totalLikes = models.IntegerField(default = 0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.slug


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=128, null=False)
    profilePicture = models.ImageField(null=False, upload_to='profilePics/', default='images/blank_pfp.png')
    bio = models.TextField(max_length=1000)
    totalLikes = models.IntegerField(default=0)
    liked = models.ManyToManyField('Image', default=None)
    slug = models.SlugField(null=True, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username

class Image(models.Model):
    name = models.CharField(max_length=128, null = False)
    isAI = models.BooleanField(default = False)
    file = models.ImageField(null = False, upload_to= 'images/')
    parent = models.ForeignKey('Image', on_delete=models.DO_NOTHING, null = True) ###unsure if this is the correct delete mode
    likes = models.IntegerField(default = 0)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, null=True)
    poster = models.ForeignKey(User, on_delete=models.DO_NOTHING, null = True)
    description = models.TextField(max_length=1000, unique=False)
    slug = models.SlugField()
    nameSlug = models.SlugField()
    slashSlug = models.CharField(max_length=128, default = "null")

    def save(self, *args, **kwargs):
        if self.poster == None:
            full_slug = self.name
            slash_slug = self.name
        else:
            full_slug = str(self.poster) + "-" + self.name
            slash_slug = slugify(str(self.poster)) + "/" + slugify(self.name) + "/"
        self.slug = slugify(full_slug)
        self.nameSlug = slugify(self.name)
        self.slashSlug = slash_slug


        duplicates = Image.objects.filter(slug = self.slug)
        if int(duplicates.count()) > 1:
            num = str(duplicates.count())
            self.slug = slugify(full_slug + num) #Image slug is a concatenation of the user who posted it and the name
            self.nameSlug = slugify(self.name + num)
            self.slashSlug = slash_slug[:-1] + num + "/"

        super(Image, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'images'

    def __str__(self):
        return self.slug

artecho/forms.py
from django import forms
from artecho.models import Image, Category, UserProfile
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
import re

class LoginForm(AuthenticationForm):
    password = forms.CharField(widget=forms.PasswordInput())
    username = forms.CharField(help_text="")
    class Meta:
        model = UserProfile
        fields = ('username', 'password',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    username = forms.CharField(help_text="")
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ( )

class SignUpForm(UserForm):
    password_confirm = forms.CharField(widget=forms.PasswordInput(), label='Confirm password')

    class Meta(UserForm.Meta):
        fields = UserForm.Meta.fields + ('password_confirm',)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password != password_confirm:
            self.add_error('password_confirm', 'Passwords must match')

        return cleaned_data
class ImageForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Select a category")
    class Meta:
        model = Image
        fields = ('name', 'isAI', 'category', 'description', )
        labels = {
            'isAI': 'Is this image AI generated?',
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'profilePicture' ]
        labels = {
            'totalLikes': 'Total Likes',
            'profilePicture': 'Profile Picture',
        }
class UserForm(forms.ModelForm):
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if re.match(r'^\d+$', username):
            raise forms.ValidationError("Username cannot be entirely numeric")
        return username
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
    
class UserProfileForm(forms.ModelForm):
     class Meta:
        model = UserProfile
        fields = [ ] 
        labels = {
            'totalLikes': 'Total Likes',
        }

artecho/views.py
from django.shortcuts import render
from django.http import HttpResponse, FileResponse, Http404, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.shortcuts import redirect
from artecho.forms import UserProfileForm, ImageForm, ProfileForm, UserForm
from artecho.models import Image, Category, UserProfile
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404
from datetime import datetime
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt

def index(request):
    try:
        display_images = Image.objects.order_by('-likes')[:30]
        user_profile=UserProfile.objects.get(user=request.user)
        context_dict = {'boldmessage': 'Welcome to ArtEcho!',
                        'user_profile': user_profile,
                        'display_images': display_images
                        }
    except:
        display_images = Image.objects.order_by('-likes')[:30]
        context_dict = {'boldmessage': 'Welcome to ArtEcho!',
                        'display_images': display_images
                        }
    return render(request, 'artecho/index.html', context=context_dict)

def card(request):
    return render(request, 'artecho/base-card.html')

def add_root(request):
    context = {}
    try:
        context['user_profile'] = UserProfile.objects.get(user=request.user)
    except:
        pass
    return render(request, 'artecho/add-root.html', context= context)

def about(request):
    context_dict = {'boldmessage': "This is about ArtEcho"}
    print(request.method)
    print(request.user)
    return render(request, 'artecho/about.html', context=context_dict)

def tree_view(request, user_name, image_title):
    slug = f"{user_name}-{image_title}"
    image = Image.objects.filter(slug=slug).first()


    if image is None:
        raise Http404("Image does not exist")
    

    context = {
        'image': image,
        'parent':image.parent,
        'children': Image.objects.filter(parent = image)
    }
    try:
        context['user_profile'] = UserProfile.objects.get(user=request.user)
    except:
        pass
    return render(request, 'artecho/tree-view.html', context)

def user_logout(request):
    logout(request)
    return(redirect(reverse('artecho:index')))

def signup(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,
                  'artecho/signup.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days >= 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits
def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    response = redirect(reverse('artecho:index'))
                    response.set_cookie('auth_token', 'repsonse_token', max_age=3600)
                    return response
                else:
                    return HttpResponse("Your artecho account is disabled.")
            else:
                print(f"Invalid login details: {username}, {password}")
                return HttpResponse("Invalid login details supplied.")
    else:
        form = AuthenticationForm()
    return render(request, 'artecho/login.html', {'form': form})

@login_required
def add_root(request):
    
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.save()
            return redirect(reverse('artecho:index'))
        else:
            print(form.errors)
    else:
        form = ImageForm()
    context = {'form': form}
    try:
        context['user_profile'] = UserProfile.objects.get(user=request.user)
    except:
        pass
    return render(request, 'artecho/add-root.html', context= context)

@login_required
def add_child(request, user_name, image_title):
    slug = f"{user_name}-{image_title}"
    parent = Image.objects.filter(slug=slug).first()

    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.poster = request.user
            image.parent = parent
            image.save()
            return redirect(reverse('artecho:index'))
        else:
            print(form.errors)
    else:
        form = ImageForm()
    context = {'form': form,
               'parent': parent,
               'user_profile': UserProfile.objects.get(user=request.user)
               }
    return render(request, 'artecho/add-child.html', context=context)

def search_results(request):
    query = request.GET.get('q')
    
    users = User.objects.filter(username__icontains=query) if query else []
    
    categories = Category.objects.filter(name__icontains=query) if query else []
    
    images = Image.objects.filter(category__in=categories) if categories else []

    image_search_results = Image.objects.filter(name__icontains=query) if query else []
    context = {'users': users, 'images': images,'image_search_results': image_search_results, 'query': query}
    try:
        context['user_profile'] = UserProfile.objects.get(user=request.user)
    except:
        pass
    
    return render(request, 'artecho/search_results.html', context=context)

@login_required
def profile_edit(request, slug):
    user_profile = get_object_or_404(UserProfile, slug=slug)
    profile = UserProfile.objects.get(slug=slug)
    if request.user != profile.user:
        return redirect('login')
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('profile', slug=slug)
    else:
        form = ProfileForm(instance=user_profile)
    return render(request, 'artecho/profile-edit.html', {'form': form})

def profile(request, slug):
    current_user_profile = get_object_or_404(UserProfile, slug=slug)
    current_user= current_user_profile.user
    images = Image.objects.filter(poster = current_user_profile.user)[:10]
    context_dict = {'current_user_profile': current_user_profile,
                    'current_slug': slug,
                    'images': images,
                    'current_user': current_user
                    }
    try:
        context_dict['user_profile'] = UserProfile.objects.get(user=request.user)
    except:
        pass
    return render(request, 'artecho/profile.html', context_dict)

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    if request.user != image.poster:
        return redirect('index')
    if request.method == 'POST':
        image.file.delete(save=True)
        image.delete()
        return redirect('profile', slug=request.user.userprofile.slug)


def download_image(request, slug):
    image = get_object_or_404(Image, slug=slug)
    file_path = image.file.path
    response = FileResponse(open(file_path, 'rb'))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = f'attachment; filename="{image.name}"'
    return response

@csrf_exempt
@require_POST
def like_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.likes += 1
    image.save()
    return JsonResponse({'likes': image.likes})

templates/artecho/about.html
<!DOCTYPE html>
{% extends 'artecho/base-card.html' %}
{% load static %}
{% block title_block %}
    <title>About | ArtEcho</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/about_card.css' %}">
{% endblock %}

{% block card_content %}

        

    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleInterval" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleInterval" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleInterval" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="5750">
                <img src="{% static 'images/aboutpage-ls.jpg' %}" class="d-block w-100" alt="...">
                <div id="hero-logo" class="heading-container">
                    <h2>ArtEcho</h2>
                </div>
                <div id="hero-title">
                    <p>ABOUT<p>
                </div>
                <div id="hero1-info1">
                    <i class="fa-solid fa-circle"></i><p>Discover Limitless Inspiration </p> 
                </div>
                <div id="hero1-info2">
                    <i class="fa-solid fa-circle"></i><p>Contribute to the Tapestry of Art</p>
                </div>
                <div id="hero1-info3">
                    <i class="fa-solid fa-circle"></i><p>Forge Meaningful Connections</p> 
                </div>
                <div id="socials">
                    <li>
                        <i class="fa-brands fa-twitter"></i>
                        <i class="fa-brands fa-instagram"></i>
                        <i class="fa-brands fa-facebook"></i>
                        <i class="fa-brands fa-linkedin"></i>
                    </li>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="5750">
                <img src="{% static 'images/ai-artist.jpeg' %}" class="d-block w-100" alt="...">
                <div id="hero-logo" class="heading-container">
                    <h2>ArtEcho</h2>
                </div>
                <div id="hero-info1">
                    <i class="fa-solid fa-circle"></i><p>Many artists are experimenting with collaborative projects involving AI systems. </p> 
                </div>
                <div id="hero-info2">
                    <i class="fa-solid fa-circle"></i><p>These collaborations can take various forms, from using AI to augment traditional artistic processes to actively involving AI algorithms in the creation process. </p>
                </div>
                <div id="hero-info3">
                    <i class="fa-solid fa-circle"></i><p>Some artists see AI as a co-creator, while others view it as a tool or medium for exploration.</p> 
                </div>
                
                <div id="socials">
                    <li>
                        <i class="fa-brands fa-twitter"></i>
                        <i class="fa-brands fa-instagram"></i>
                        <i class="fa-brands fa-facebook"></i>
                        <i class="fa-brands fa-linkedin"></i>
                    </li>
                </div>
                
            </div>
            <div class="carousel-item" data-bs-interval="5750">
                <img src="{% static 'images/ai-tech.jpeg' %}" class="d-block w-100" alt="...">  
                <<div id="hero-logo" class="heading-container">
                    <h2>ArtEcho</h2>
                </div>
                <div id="hero2-info1">
                    <i class="fa-solid fa-circle"></i><p>Generative art, which involves the use of autonomous systems such as algorithms or AI, has gained prominence in recent years.</p> 
                </div>
                <div id="hero2-info2">
                    <i class="fa-solid fa-circle"></i><p>AI algorithms can generate art autonomously, blurring the lines between the artist and the artwork itself</p>
                </div>
                <div id="hero2-info3">
                    <i class="fa-solid fa-circle"></i> <p>This form of art raises questions about authorship, creativity, and the role of human intention in artistic creation.</p> 
                </div>
                <div id="socials">
                    <li>
                        <i class="fa-brands fa-twitter"></i>
                        <i class="fa-brands fa-instagram"></i>
                        <i class="fa-brands fa-facebook"></i>
                        <i class="fa-brands fa-linkedin"></i>
                    </li>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden"><i class="fa-solid fa-chevron-left"></i></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden"><i class="fa-solid fa-chevron-right"></i></span>
        </button>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <div class="main-body">
        <div class="card-container">
            <div class="about-container">
                <p>
                    Welcome to Artecho, a vibrant community where art meets innovation. Here you can share your masterpieces or discover new dimensions of creativity through AI. 
                </p>
                <p>
                    Upload your artwork, whether human or AI-created, and explore. Watch as your image transforms, offering a new perspective. Or dive into the communities 
                    creations and add your own unique touch.
                </p>
                <p>
                    Join forces with artists and tech enthusiasts alike. Whether you're starting with your own peice or iterating on someone else's, every image is a branch of endless possibilities.
                </p>
                <p>
                    ready to Echo your creativity? Start exploring, creating and sharing on ArtEcho today.
                </p>
            </div>
            <div class="navigation-links">
                <div id="nav-container"><p>Already a member? <a class="login-button" href="{% url 'artecho:login' %}">Log in</a></p></div>
               <div id="nav-container"><p>New here? <a class="signup-button" href="{% url 'artecho:signup' %}">Sign up</a></p></div>
                <div id="nav-container"><p>Get back to <a class="home-button" href="{% url 'artecho:index' %}">Home Page</a></p></div>
            </div>
        </div>
    </div>
    <footer>
        <p>© 2024 ArtEcho</p>
        <li>
            <a href="{% url 'artecho:index' %}">Home</a>
            <a href="{% url 'artecho:about' %}">About</a>
            <a href="{% url 'artecho:login' %}">Login</a>
            <a href="{% url 'artecho:signup' %}">Signup</a>
        </li>
    </footer>
{% endblock %}

templates/artecho/base-navbar.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        {% block title_block %}
            <title> ArtEcho </title>
        {% endblock %}
        <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    </head>
    <body>
        <nav id="topnav">
            <a class="nav-button" id="artecho-link" href="{% url 'artecho:index' %}">ArtEcho</a>
            <form action="{% url 'artecho:search' %}" method="get">
                <input name="q" type="text" placeholder="Search.." value="{{ request.GET.q }}">
            </form>
            <a class="nav-button" id="about-link" href="{% url 'artecho:about' %}">i</a>
            {% if user.is_authenticated %}
            <a class="nav-button" id="add-root" href="{% url 'artecho:add_root' %}">+</a>
            <div class="dropdown">
                <img id="profile-pic" src="{{ user_profile.profilePicture.url }}" alt="Profile" class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <p>{{ user.username }}</p>
                    <a href="{% url 'profile' slug=user.userprofile.slug %}">Profile</a>
                    <a class="dropdown-item"id="logout-link" href="{% url 'artecho:logout' %}">Logout</a>
                </div>
            </div>
            {% else %}
            <a class="nav-button" id="signup-link" href="{% url 'artecho:signup'%}">Sign up</a>
            <a class="nav-button" id="login-link" href="{% url 'artecho:login' %}">Log in</a>
            {% endif %}
        </nav>
        
        <div id="blank_space">
            <!-- This blank space is to cover #topnav's area, so #content don't go under it -->
        </div>

        <div id="content">
            {% block body_block %}
            {% endblock %}
        </div>
        <footer>
            <p>© 2024 ArtEcho</p>
            <li>
                <a href="{% url 'artecho:index' %}">Home</a>
                <a href="{% url 'artecho:about' %}">About</a>
                <a href="{% url 'artecho:login' %}">Login</a>
                <a href="{% url 'artecho:signup' %}">Signup</a>
            </li>
        </footer>
    </body>
</html>

templates/artecho/index.html
<!DOCTYPE html>
{% extends 'artecho/base-navbar.html' %}
{% load static %}

{% block title_block %}
    <title> ArtEcho </title>
    <link rel="stylesheet" href="{% static 'css/figure_display.css' %}">
    <link rel="stylesheet" href="{% static 'css/figure_tiling.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block body_block %}

<div class="container"> 
    {% if display_images %}
        {% for image in display_images %}
            {% if image.slug == "base_root" %}
            {% else %}
                <figure>
                    <a href="{{ image.slashSlug }}">
                        <img src="{{ image.file.url }}" 
                        alt="{{image.name}}" />
                    </a>
                    <div class="caption-wrapper">
                        <figcaption class="username"><a href="{% url 'artecho:profile' image.poster.userprofile.slug %}">{{image.poster}}</a></figcaption>
                        <div class="likes-download-wrapper">
                            <figcaption class="likes" data-id="{{image.id}}"><i class="fa-regular fa-heart"></i> <span>{{image.likes}}</span></figcaption>
                            <figcaption class="download"><a href="{% url 'artecho:download_image' image.slug %}"><i class="fa-solid fa-download fa-bounce"></i></a></figcaption>
                        </div>
                    </div>
                </figure>
            {% endif %}
        {% endfor %}
    {% else %}
        <strong>No images were found</strong>
    {% endif %}
    <script src="{% static 'js/like.js' %}"></script>
</div>

{% endblock %}

templates/artecho/login.html
<!DOCTYPE html>
{% extends 'artecho/base-card.html' %}
{% load static %}
{% block title_block %}
    <title>Log In | ArtEcho</title>
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
{% endblock %}

{% block card_content %}
    <div class="login-container">
        <h2>ArtEcho</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-container">
                <button id="login" type="submit">Log In</button>
            </div>
        </form>
        <p>Don't have an account? <a href="{% url 'artecho:signup'%}">Sign Up</a></p>
    </div>
    <div class="homebtn">
        <a href="{% url 'artecho:index' %}">Home</a>
    </div>
{% endblock %}

templates/artecho/profile.html
<!DOCTYPE html>
{% extends 'artecho/base-navbar.html' %}
{% load static %}

{% block title_block %}
    <title>{{ current_user_profile.user.username }} | ArtEcho</title>
    <link rel="stylesheet" href="{% static 'css/figure_display.css' %}">
    <link rel="stylesheet" href="{% static 'css/figure_tiling.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile_details.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block body_block %}
    <div id="profile-details">
        <img id="profile-pic" src="{{ current_user_profile.profilePicture.url }}" alt="Profile picture">
        <div id="description">
            <p>{{ current_user_profile.user.username }}</p>
            <p class="bio">{{ current_user_profile.user.bio }}</p>
            <p>Total Likes: {{ current_user_profile.user.totalLikes }}</p>
        </div>
        {% if user_profile.slug == current_slug %}
            <div class="edit-btn" id="Edit">
                <a href="#">Edit</a>
            </div>
        {% else %}    
        {% endif %}
    </div>

    <div class="container">
        {% if images %}
            {% for image in images %}
                <figure>
                    <a href="{% url 'artecho:tree' image.poster.userprofile.slug image.nameSlug%}">
                        <img src="{{ image.file.url }}">
                    </a>
                    <form method="POST" action="{% url 'delete_image' image.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-button"><i class="fa-solid fa-x"></i></button>
                    </form>
                    <div class="caption-wrapper">
                        <figcaption class="username"><a href="#">{{image.poster}}</a></figcaption>
                        <div class="likes-download-wrapper">
                            <figcaption class="likes"><i class="fa-regular fa-heart"></i> {{image.likes}}</figcaption>
                            <figcaption class="download"><a href="{% url 'artecho:download_image' image.slug %}"><i class="fa-solid fa-download fa-bounce"></i></a></figcaption>
                        </div>
                    </div>
                </figure>
            {% endfor %}
        {% else %}
            <strong>No images have been posted</strong>
        {% endif %}
    </div>
{% endblock %}